name: ReplaceMode
main: deadeye.ReplaceMode.ReplaceMode
version: 0.1

commands:
  replacemode:
    description: Enters ReplaceMode and modifies ReplaceMode id.
    usage: |
           /<command> id [player]
           Example: /<command>  id - toggles ReplaceMode and/or sets id.
           Example: /<command> id Deadeye - toggles ReplaceMode for Deadeye and/or sets id.
    aliases: rpm